### ISSUE TITLE
Video: spam join video button crashes the app

### ISSUE THREAD

**Issue by frankemax** [mconf/bbb-mobile-sdk#359]
![Image](https://github.com/mconf/bbb-mobile-sdk/assets/42683590/2c626a67-3d11-44ae-b694-0d9133921945)

**Comment by frankemax** [comment]
```
2023-08-16 17:14:55.147 31012-31084 unknown:ReactNative     org.bbb.mobilesdk                    E  Exception in native call
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.Request$Builder.url, parameter url
                                                                                                    	at okhttp3.Request$Builder.url(Unknown Source:3)
                                                                                                    	at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:106)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by frankemax** [comment]
Closing for now... if this reappears will be reopened
